# Sample Netplan file
#
# Uses systemd-networkd over NetworkManager as it is recommended for simple server setups.
#
# Bridges are only required if VMs need to be operated in bridged mode and not
# their default NATted mode. This is for VMs spun up using KVM/QEMU.
#
# virbr0 should not be mentioned in the file as it is not bound to any physical
# interface.

network:
    version: 2
    renderer: networkd
    ethernets:
        eno1:
            dhcp4: true
            dhcp-identifier: mac
        eno2:
            dhcp4: true
            dhcp-identifier: mac
    bridges:
        br0:
            dhcp4: true
            dhcp-identifier: mac
            interfaces:
                - eno2
        br1: # Secondary/optional bridge in case VMs need multiple interfaces
            dhcp4: true
            dhcp-identifier: mac
            interfaces:
                - eno1
